= Lenny Primak & Flow Logix, Inc.
:jbake-type: page
:description: Home Page
:idprefix:
:linkattrs:
:jbake-status: published

== About Me
=== Early Years
Grew up in Ukraine until 12 years of age +
Came to the USA at 13 years of age and lived in NYC +
Child Prodigy Violinist until 14 years of age, played at Carnegie Hall +

=== Early Career
Worked at major Wall Street Investmend Banks, focusing on distributed real-time trading systems +
Became a Pilot at 21 years of age +
Inventor +
Started own company at 26 years of age +
Won numerous patents +

=== Aviation
Achieved ATP - Highest level of Pilot Certificate
Earned a Rotorcraft-Helicopter Certificate
Worked for ExpressJet Airlines since 2007 +
Jet Captain at Silverhawk Aviation since 2021 +

=== Software Development
Problem-solver +

=== Family Life
Fix Appliances, HVAC and other things around the house

link:/my-info/resume-pilot.html[Pilot Resume] +
link:/my-info/resume-tech.html[Technology Resume] +
link:/my-info/lenny-bio.html[Biography] +
https://www.icloud.com/sharedalbum/#B0SG4TcsmGVcu2X[Pictures of Me, window="lenny-pix"] +
link:[Photo Albums (future)]

== Things I want you to know about me
- Played at Carnegie Hall
- Started a Technology Company (flowlogix.com)

== Family Life
Married and have a wonderful daughter
- Jill Primak
- Anya Primak

== BattleCop
XXX link XXX

== Open Source Contributions
- Payara
- Hazelcast Hero
- OpenSSL
- Arquillian
- Arquillian Suite Extension
- Jakarta EL (Expression Language)
- Jakarta Mojarra JSF
- Jakarta Tyrus (WebSocket)
- Eclipse MicroProfile
- OmniFaces
- Oshi
- Eclipse Weld Project (CDI)
- Eclipse Jersey
- Underscore.js

== Resources
link:/mail[Webmail Access] +
link:/ssh[Secure Terminal Access]

== Links
https://flowlogix.com[Flow Logix, Inc.^] +
https://silverhawkaviation.com[Silverhawk Aviation^] +
https://nycairservice.com[NYC Air Service^] +
https://industriallogic.com[Industrial Logic, Inc.^] +
https://killerinnovations.com[Killer Innovations Podcast^] +
https://www.nycelite.com[NYC Elite Gymnastics, Inc.^] +

== Patents
https://patft1.uspto.gov/netacgi/nph-Parser?patentnumber=6389448[Patent 6,389,448 - System and method for Load Balancing^] +
https://patft1.uspto.gov/netacgi/nph-Parser?patentnumber=6598077[Patent 6,598,077 - System and method for dynamic content routing^] +
https://patft1.uspto.gov/netacgi/nph-Parser?patentnumber=7443311[Patent 7,443,311 - Chair mounted system for control based on use of chair^]
