= Lenny Primak & Flow Logix, Inc.
:jbake-type: page
:description: Home Page
:idprefix:
:linkattrs:
:jbake-status: published

== About Me
=== Early Years
Grew up in Ukraine until 12 years of age, when my family decided to emigrate from the former USSR. I Came to the USA at 13 years of age. We settled in New York City. I was child prodigy ciolinist until 14 years of age, and played at Carnegie Hall.

=== Technology and Wall Street Career
Got my first big break at major Wall Street investmend Bank at 17 years of age, focusing on distributed real-time trading systems. +
Became a Pilot at 21 years of age +
Focusing on invention and innovation, winning numerous patents along thw way. +
Started own technology company at 26 years of age.

=== Aviation
Achieved an ATP certificate, which is the highest level of pilot certificate in existance +
Earned a Rotorcraft-Helicopter certificate +
Worked for ExpressJet Airlines since 2007 +
Jet Captain at Silverhawk Aviation since 2021 +

=== Software Development
Specializing in solving most difficult problems with highly performant and distributed systems.
Highly experienced in Agile methodology, test-driven development, refactoring and complex debugging tasks.

=== Family Life
Married to Jill and have a wonderful 6-year-old daughter Anya

=== Hobbies
Fix Appliances, HVAC and other things around the house

link:/my-info/resume-pilot.html[Pilot Resume] +
link:/my-info/resume-tech.html[Technology Resume] +
link:/my-info/lenny-bio.html[Biography] +
https://www.icloud.com/sharedalbum/#B0SG4TcsmGVcu2X[Pictures of Me, window="lenny-pix"] +
link:[Photo Albums (future)]

== Open Source Contributions
- Payara
- Hazelcast Hero
- OpenSSL
- Arquillian
- Arquillian Suite Extension
- Jakarta EL (Expression Language)
- Jakarta Mojarra JSF
- Jakarta Tyrus (WebSocket)
- Eclipse MicroProfile
- OmniFaces
- Oshi
- Eclipse Weld Project (CDI)
- Eclipse Jersey
- Underscore.js

== Resources
link:/mail[Webmail Access] +
link:/ssh[Secure Terminal Access]

== Some of my favorite things
https://flowlogix.com[Flow Logix, Inc.^] +
My Corporate entity for consulting and other endevours. +

=== Technology
https://killerinnovations.com[Killer Innovations Podcast^] +
One of the best Podcasts I listen to. +
https://industriallogic.com[Industrial Logic, Inc.^] +
Agile coaching. +
https://payara.fish[Payara Platform^] +
Java application platform and rUntime.

=== Aviation
https://silverhawkaviation.com[Silverhawk Aviation^] +
Best charter and fractional company in the Midwest. +
https://nycairservice.com[NYC Air Service^] +
Best flight instruction and air tour in NYC. +

=== Music
https://battlecopmusic.com[BattleCop^] +
My wife's rock'n'noll band.

=== Child Development
https://natureexplore.org[Nature Explore^] +
My wife works there. Get those kids outside! +
https://dimensionsed.org[Dimensions Education^] +
Early childhood education program. +
https://www.nycelite.com[NYC Elite Gymnastics, Inc.^] +
Best gymnastics schools in NYC.

== Patents
https://patft1.uspto.gov/netacgi/nph-Parser?patentnumber=6389448[Patent 6,389,448 - System and method for Load Balancing^] +
https://patft1.uspto.gov/netacgi/nph-Parser?patentnumber=6598077[Patent 6,598,077 - System and method for dynamic content routing^] +
https://patft1.uspto.gov/netacgi/nph-Parser?patentnumber=7443311[Patent 7,443,311 - Chair mounted system for control based on use of chair^]
