= Technology
:jbake-type: page
:description: Technology and Software Development
:idprefix:
:linkattrs:
:jbake-status: published

== A guy in Nebraska maintaining Open Source software

Specializing in solving difficult problems with real-time, high performance and distributed systems. +
Highly experienced in Agile methodology, test-driven development, refactoring and complex debugging tasks.

== Patents
https://image-ppubs.uspto.gov/dirsearch-public/print/downloadPdf/6389448[Patent 6,389,448 - System and method for Load Balancing^] +
https://image-ppubs.uspto.gov/dirsearch-public/print/downloadPdf/6598077[Patent 6,598,077 - System and method for dynamic content routing^] +
https://image-ppubs.uspto.gov/dirsearch-public/print/downloadPdf/7443311[Patent 7,443,311 - Chair mounted system for control based on use of chair^]

== Memberships and Associations
- Member of Apache Software Foundation - Shiro PMC Chair
- Jakarta EE Contributor
- Member of Eclipse Foundation (Jakarta EE)

++++
<iframe src="https://github.com/sponsors/lprimak/button" title="Sponsor lprimak" height="35" width="116" style="border: 0;"></iframe>
++++

== Open Source Contributions
- https://github.com/flowlogix/flowlogix[Flow Logix Jakarta EE Components^]
- https://payara.fish[Payara^]
- https://hazelcast.com/dev-community/heroes/[Hazelcast Hero^]
- Apache Shiro Security PMC Chair
- Jakarta EE Platform
- Apache Maven
- PrimeFaces
- OpenSSL
- Arquillian
- Arquillian Suite Extension
- Jakarta EL (Expression Language)
- Jakarta Mojarra JSF
- Jakarta Tyrus (WebSocket)
- Jenkins CI
- Eclipse Jetty
- Eclipse MicroProfile
- OmniFaces
- Oshi
- Eclipse Weld Project (CDI)
- Eclipse Jersey
- Underscore.js

---
View my link:resume/resume.html[Resume^] (link:resume/resume.pdf[PDF^])
