#!/bin/bash -p

letsencrypt_dir=$HOME/letsencrypt/live/payara.hope.nyc.ny.us
domain_dir=$HOME/payara/domains/website/config

openssl pkcs12 -export -in $letsencrypt_dir/cert.pem -inkey $letsencrypt_dir/privkey.pem -out $letsencrypt_dir/cert.p12 -name hope.crt -password pass:changeit
keytool -importkeystore -destkeystore $domain_dir/keystore.jks -srckeystore $letsencrypt_dir/cert.p12 -srcstoretype PKCS12 -srcstorepass changeit -deststorepass changeit -alias hope.crt --noprompt
keytool -importkeystore -destkeystore $domain_dir/cacerts.jks -srckeystore $letsencrypt_dir/cert.p12 -srcstoretype PKCS12 -srcstorepass changeit -deststorepass changeit -alias hope.crt --noprompt

rm -f $letsencrypt_dir/cert.p12

asadmin set configs.config.server-config.network-config.network-listeners.network-listener.http-listener-2.enabled=false
asadmin set configs.config.server-config.network-config.network-listeners.network-listener.http-listener-2.enabled=true

