#!/bin/bash -p

letsencrypt_dir=$HOME/letsencrypt

certbot certonly --webroot \
-d payara.hope.nyc.ny.us \
--webroot-path $HOME/payara/domains/website/docroot \
--logs-dir $letsencrypt_dir/var/log --config-dir $letsencrypt_dir \
--work-dir $letsencrypt_dir/var/lib

letsencrypt-payara
