jenkins:
  securityRealm:
    local:
      users:
      - id: "admin"
        name: "Admin"
        properties:
        - mailer:
            emailAddress: "admin@flowlogix.com"
  authorizationStrategy:
    globalMatrix:
      permissions:
      - "Agent/Build:admin"
      - "Agent/Build:authenticated"
      - "Agent/Configure:admin"
      - "Agent/Configure:authenticated"
      - "Agent/Connect:admin"
      - "Agent/Connect:authenticated"
      - "Agent/Create:admin"
      - "Agent/Create:authenticated"
      - "Agent/Delete:admin"
      - "Agent/Delete:authenticated"
      - "Agent/Disconnect:admin"
      - "Agent/Disconnect:authenticated"
      - "Credentials/Create:admin"
      - "Credentials/Create:authenticated"
      - "Credentials/Delete:admin"
      - "Credentials/Delete:authenticated"
      - "Credentials/ManageDomains:admin"
      - "Credentials/ManageDomains:authenticated"
      - "Credentials/Update:admin"
      - "Credentials/Update:authenticated"
      - "Credentials/View:admin"
      - "Credentials/View:authenticated"
      - "Job Config History/DeleteEntry:admin"
      - "Job Config History/DeleteEntry:authenticated"
      - "Job/Build:admin"
      - "Job/Build:authenticated"
      - "Job/Cancel:admin"
      - "Job/Cancel:authenticated"
      - "Job/Configure:admin"
      - "Job/Configure:authenticated"
      - "Job/Create:admin"
      - "Job/Create:authenticated"
      - "Job/Delete:admin"
      - "Job/Delete:authenticated"
      - "Job/Discover:admin"
      - "Job/Discover:authenticated"
      - "Job/Move:admin"
      - "Job/Move:authenticated"
      - "Job/Read:admin"
      - "Job/Read:anonymous"
      - "Job/Read:authenticated"
      - "Job/Workspace:admin"
      - "Job/Workspace:authenticated"
      - "Lockable Resources/Reserve:admin"
      - "Lockable Resources/Reserve:authenticated"
      - "Lockable Resources/Unlock:admin"
      - "Lockable Resources/Unlock:authenticated"
      - "Lockable Resources/View:admin"
      - "Lockable Resources/View:authenticated"
      - "Overall/Administer:admin"
      - "Overall/Read:admin"
      - "Overall/Read:anonymous"
      - "Overall/Read:authenticated"
      - "Run/Artifacts:admin"
      - "Run/Artifacts:authenticated"
      - "Run/Delete:admin"
      - "Run/Delete:authenticated"
      - "Run/Replay:admin"
      - "Run/Replay:authenticated"
      - "Run/Update:admin"
      - "Run/Update:authenticated"
      - "SCM/Tag:admin"
      - "SCM/Tag:authenticated"
      - "View/Configure:admin"
      - "View/Configure:authenticated"
      - "View/Create:admin"
      - "View/Create:authenticated"
      - "View/Delete:admin"
      - "View/Delete:authenticated"
      - "View/Read:admin"
      - "View/Read:anonymous"
      - "View/Read:authenticated"
unclassified:
  gitHubPluginConfig:
    configs:
    - credentialsId: "3cddf56f-7e59-4901-a779-b4326d2bb3c9"
      name: "FlowLogix WebHook Auth"
    hookSecretConfigs:
    - credentialsId: "3cddf56f-7e59-4901-a779-b4326d2bb3c9"
  globalDefaultFlowDurabilityLevel:
    durabilityHint: PERFORMANCE_OPTIMIZED
  location:
    adminAddress: "admin@flowlogix.com"
    url: "https://jenkins.hope.nyc.ny.us/"
  buildDiscarders:
    configuredBuildDiscarders:
    - simpleBuildDiscarder:
        discarder:
          logRotator:
            daysToKeepStr: "10"
            numToKeepStr: "10"

