jenkins:
  securityRealm:
    local:
      users:
      - id: "admin"
        name: "Admin"
        properties:
        - mailer:
            emailAddress: "admin@flowlogix.com"
  globalNodeProperties:
  - envVars:
      env:
      - key: "MAVEN_OPTS"
        value: "-Dwebdriver.chrome.driver=^${HOME}/apps/chromedriver/current/chromedriver"
  authorizationStrategy:
    globalMatrix:
      permissions:
      - "GROUP:Agent/Build:authenticated"
      - "GROUP:Agent/Configure:authenticated"
      - "GROUP:Agent/Connect:authenticated"
      - "GROUP:Agent/Create:authenticated"
      - "GROUP:Agent/Delete:authenticated"
      - "GROUP:Agent/Disconnect:authenticated"
      - "GROUP:Credentials/Create:authenticated"
      - "GROUP:Credentials/Delete:authenticated"
      - "GROUP:Credentials/ManageDomains:authenticated"
      - "GROUP:Credentials/Update:authenticated"
      - "GROUP:Credentials/View:authenticated"
      - "GROUP:Job Config History/DeleteEntry:authenticated"
      - "GROUP:Job/Build:authenticated"
      - "GROUP:Job/Cancel:authenticated"
      - "GROUP:Job/Configure:authenticated"
      - "GROUP:Job/Create:authenticated"
      - "GROUP:Job/Delete:authenticated"
      - "GROUP:Job/Discover:authenticated"
      - "GROUP:Job/Move:authenticated"
      - "GROUP:Job/Read:authenticated"
      - "GROUP:Job/Workspace:authenticated"
      - "GROUP:Lockable Resources/Reserve:authenticated"
      - "GROUP:Lockable Resources/Unlock:authenticated"
      - "GROUP:Lockable Resources/View:authenticated"
      - "GROUP:Overall/Read:authenticated"
      - "GROUP:Run/Artifacts:authenticated"
      - "GROUP:Run/Delete:authenticated"
      - "GROUP:Run/Replay:authenticated"
      - "GROUP:Run/Update:authenticated"
      - "GROUP:SCM/Tag:authenticated"
      - "GROUP:View/Configure:authenticated"
      - "GROUP:View/Create:authenticated"
      - "GROUP:View/Delete:authenticated"
      - "GROUP:View/Read:authenticated"
      - "USER:Agent/Build:admin"
      - "USER:Agent/Configure:admin"
      - "USER:Agent/Connect:admin"
      - "USER:Agent/Create:admin"
      - "USER:Agent/Delete:admin"
      - "USER:Agent/Disconnect:admin"
      - "USER:Credentials/Create:admin"
      - "USER:Credentials/Delete:admin"
      - "USER:Credentials/ManageDomains:admin"
      - "USER:Credentials/Update:admin"
      - "USER:Credentials/View:admin"
      - "USER:Job Config History/DeleteEntry:admin"
      - "USER:Job/Build:admin"
      - "USER:Job/Cancel:admin"
      - "USER:Job/Configure:admin"
      - "USER:Job/Create:admin"
      - "USER:Job/Delete:admin"
      - "USER:Job/Discover:admin"
      - "USER:Job/Move:admin"
      - "USER:Job/Read:admin"
      - "USER:Job/Read:anonymous"
      - "USER:Job/Workspace:admin"
      - "USER:Lockable Resources/Reserve:admin"
      - "USER:Lockable Resources/Unlock:admin"
      - "USER:Lockable Resources/View:admin"
      - "USER:Overall/Administer:admin"
      - "USER:Overall/Read:admin"
      - "USER:Overall/Read:anonymous"
      - "USER:Run/Artifacts:admin"
      - "USER:Run/Delete:admin"
      - "USER:Run/Replay:admin"
      - "USER:Run/Update:admin"
      - "USER:SCM/Tag:admin"
      - "USER:View/Configure:admin"
      - "USER:View/Create:admin"
      - "USER:View/Delete:admin"
      - "USER:View/Read:admin"
      - "USER:View/Read:anonymous"
security:
  scriptApproval:
    approvedSignatures:
    - "method java.lang.CharSequence isEmpty"
unclassified:
  gitHubPluginConfig:
    configs:
    - credentialsId: "3cddf56f-7e59-4901-a779-b4326d2bb3c9"
      name: "FlowLogix WebHook Auth"
    hookSecretConfigs:
    - credentialsId: "3cddf56f-7e59-4901-a779-b4326d2bb3c9"
  globalDefaultFlowDurabilityLevel:
    durabilityHint: PERFORMANCE_OPTIMIZED
  location:
    adminAddress: "admin@flowlogix.com"
    url: "https://jenkins.hope.nyc.ny.us/"
  buildDiscarders:
    configuredBuildDiscarders:
    - simpleBuildDiscarder:
        discarder:
          logRotator:
            daysToKeepStr: "10"
            numToKeepStr: "10"

