credentials:
  system:
    domainCredentials:
    - credentials:
      - string:
          description: "WebHook Secret - Token and Secret itself"
          id: "3cddf56f-7e59-4901-a779-b4326d2bb3c9"
          scope: GLOBAL
          secret: "{AQAAABAAAAAwirFsgdUXrbHHrREGSEpt6PHKGDbO/M59f3/moyM+7OlyZqEt4koPvG1TtdjBnhDJyL3gL8ma9HZt0V50bQRzRg==}"
      - usernamePassword:
          description: "GitHub Repo Access Token"
          id: "dd067490-e408-45cb-b911-d825906a05ee"
          password: "{AQAAABAAAAAwQXHmD1qAEEN+tpkJbS1SPOKfgLP0JTp596PP8a6xf7+6sL3FBxkY6rxBltoMUvcOQTyG8FhesEWov+2n69hVCw==}"
          scope: GLOBAL
          username: "accesstoken"
          usernameSecret: true
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    globalMatrix:
      permissions:
      - "GROUP:Agent/Build:authenticated"
      - "GROUP:Agent/Configure:authenticated"
      - "GROUP:Agent/Connect:authenticated"
      - "GROUP:Agent/Create:authenticated"
      - "GROUP:Agent/Delete:authenticated"
      - "GROUP:Agent/Disconnect:authenticated"
      - "GROUP:Credentials/Create:authenticated"
      - "GROUP:Credentials/Delete:authenticated"
      - "GROUP:Credentials/ManageDomains:authenticated"
      - "GROUP:Credentials/Update:authenticated"
      - "GROUP:Credentials/View:authenticated"
      - "GROUP:Job Config History/DeleteEntry:authenticated"
      - "GROUP:Job/Build:authenticated"
      - "GROUP:Job/Cancel:authenticated"
      - "GROUP:Job/Configure:authenticated"
      - "GROUP:Job/Create:authenticated"
      - "GROUP:Job/Delete:authenticated"
      - "GROUP:Job/Discover:authenticated"
      - "GROUP:Job/Move:authenticated"
      - "GROUP:Job/Read:authenticated"
      - "GROUP:Job/Workspace:authenticated"
      - "GROUP:Lockable Resources/Reserve:authenticated"
      - "GROUP:Lockable Resources/Unlock:authenticated"
      - "GROUP:Lockable Resources/View:authenticated"
      - "GROUP:Overall/Read:authenticated"
      - "GROUP:Run/Artifacts:authenticated"
      - "GROUP:Run/Delete:authenticated"
      - "GROUP:Run/Replay:authenticated"
      - "GROUP:Run/Update:authenticated"
      - "GROUP:SCM/Tag:authenticated"
      - "GROUP:View/Configure:authenticated"
      - "GROUP:View/Create:authenticated"
      - "GROUP:View/Delete:authenticated"
      - "GROUP:View/Read:authenticated"
      - "USER:Agent/Build:admin"
      - "USER:Agent/Configure:admin"
      - "USER:Agent/Connect:admin"
      - "USER:Agent/Create:admin"
      - "USER:Agent/Delete:admin"
      - "USER:Agent/Disconnect:admin"
      - "USER:Credentials/Create:admin"
      - "USER:Credentials/Delete:admin"
      - "USER:Credentials/ManageDomains:admin"
      - "USER:Credentials/Update:admin"
      - "USER:Credentials/View:admin"
      - "USER:Job Config History/DeleteEntry:admin"
      - "USER:Job/Build:admin"
      - "USER:Job/Cancel:admin"
      - "USER:Job/Configure:admin"
      - "USER:Job/Create:admin"
      - "USER:Job/Delete:admin"
      - "USER:Job/Discover:admin"
      - "USER:Job/Move:admin"
      - "USER:Job/Read:admin"
      - "USER:Job/Read:anonymous"
      - "USER:Job/Workspace:admin"
      - "USER:Lockable Resources/Reserve:admin"
      - "USER:Lockable Resources/Unlock:admin"
      - "USER:Lockable Resources/View:admin"
      - "USER:Overall/Administer:admin"
      - "USER:Overall/Read:admin"
      - "USER:Overall/Read:anonymous"
      - "USER:Run/Artifacts:admin"
      - "USER:Run/Delete:admin"
      - "USER:Run/Replay:admin"
      - "USER:Run/Update:admin"
      - "USER:SCM/Tag:admin"
      - "USER:View/Configure:admin"
      - "USER:View/Create:admin"
      - "USER:View/Delete:admin"
      - "USER:View/Read:admin"
      - "USER:View/Read:anonymous"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "jenkins.diagnostics.ControllerExecutorsNoAgents"
  - "org.jenkinsci.plugins.pipeline.maven.NonProductionGradeDatabaseWarningAdministrativeMonitor"
  - "jenkins.security.QueueItemAuthenticatorMonitor"
  - "jenkins.diagnostics.ControllerExecutorsAgents"
  - "hudson.diagnosis.ReverseProxySetupMonitor"
  globalNodeProperties:
  - envVars:
      env:
      - key: "CHROME_BINARY"
        value: "^${HOME}/apps/google-chrome/97/Google Chrome.app/Contents/MacOS/Google\
          \ Chrome"
      - key: "MAVEN_ADD_OPTIONS"
        value: "-Dwebdriver.browser=firefox"
      - key: "MAVEN_OPTS"
        value: "-Dwebdriver.chrome.driver=^${HOME}/apps/chromedriver/97/chromedriver\
          \ -Dwebdriver.gecko.driver=^${HOMEBREW_PREFIX}/bin/geckodriver"
  labelAtoms:
  - name: "built-in"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        name: "Admin"
        properties:
        - favoriting:
            autofavoriteEnabled: true
        - "favorite"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - "apiToken"
        - mailer:
            emailAddress: "admin@flowlogix.com"
  slaveAgentPort: -1
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - calendar:
      columns:
      - "status"
      - "weather"
      - "jobName"
      - "lastSuccess"
      - "lastFailure"
      - "lastDuration"
      - "buildButton"
      - "favoriteColumn"
      includeRegex: ".*"
      name: "Build Timeline"
      recurse: true
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  sSHD:
    port: -1
unclassified:
  bitbucketEndpointConfiguration:
    endpoints:
    - bitbucketCloudEndpoint:
        enableCache: false
        manageHooks: false
        repositoriesCacheDuration: 0
        teamCacheDuration: 0
  buildDiscarders:
    configuredBuildDiscarders:
    - simpleBuildDiscarder:
        discarder:
          logRotator:
            daysToKeepStr: "10"
            numToKeepStr: "10"
  buildStepOperation:
    enabled: false
  casCGlobalConfig:
    configurationPath: "/Users/software/hope-website/scripts/jenkins/config.yaml"
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
    - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    watchingEnabled: false
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    configs:
    - credentialsId: "3cddf56f-7e59-4901-a779-b4326d2bb3c9"
      name: "FlowLogix WebHook Auth"
    hookSecretConfigs:
    - credentialsId: "3cddf56f-7e59-4901-a779-b4326d2bb3c9"
    hookUrl: "https://jenkins.hope.nyc.ny.us/github-webhook/"
  gitSCM:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  globalDefaultFlowDurabilityLevel:
    durabilityHint: PERFORMANCE_OPTIMIZED
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "admin@flowlogix.com"
    url: "https://jenkins.hope.nyc.ny.us/"
  mailer:
    authentication:
      password: "{AQAAABAAAAAQHeNwJE3Wq3a47M4RpKDTX/h3tPIT6q9SA5Sz0KPFXE4=}"
    charset: "UTF-8"
    useSsl: false
    useTls: false
  mavenModuleSet:
    localRepository: "default"
  pollSCM:
    pollingThreadCount: 10
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
  pipelineMaven:
    triggerDownstreamUponResultAborted: false
    triggerDownstreamUponResultFailure: false
    triggerDownstreamUponResultNotBuilt: false
    triggerDownstreamUponResultSuccess: true
    triggerDownstreamUponResultUnstable: false
